### ISSUE TITLE
Testing of backend

### ISSUE THREAD

**Issue by arora-aakansha** [Neha179/Online-MusicalInstrument-Site#40]

**Comment by arora-aakansha** [comment]
Test cases

1. Register users
2. Register multiple users with same ID
3.Login user with correct ID
4.Login user with wrong ID
5.Add product to cart
6.Add product to wish
7.Place order
8.Add wish to cart
9.Add multiple products to wish
10. Move some products to cart
11. Delete remaining products from wish
12.Remove all products from cart
13.Do for multiple users
14. repeat 8, 9, 10 , 13
15. Place order for different users at same time
16. perform above tests for different users at same time
17. see search history
18. update profile
19. change password
20. Login with new pass
21. Login and Logout
22. Add same product in cart n wish in single session
23. Add same product for multiple users 
24. Make stock 0 and add
25. Add product with stock 1 for multiple users at same time

For admin
1. login
2. add product
3. remove product
4. add multiple product
5. remove multiple product
6. view product after each test
7. update stock
8. check update
9. logout

**Comment by arora-aakansha** [comment]
@monalisa15 @KansaraDarshan 
Please add new combos in comment 
@Arya-P-Menon @Neha179

**Comment by KansaraDarshan** [comment]
admin cannot remove product
